//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWcfClient.HelloWcfServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignModel", Namespace="http://schemas.datacontract.org/2004/07/HelloWcfService")]
    [System.SerializableAttribute()]
    public partial class SignModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloWcfServiceReference.ISignService")]
    public interface ISignService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignService/SignIn", ReplyAction="http://tempuri.org/ISignService/SignInResponse")]
        string SignIn(HelloWcfClient.HelloWcfServiceReference.SignModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignService/SignIn", ReplyAction="http://tempuri.org/ISignService/SignInResponse")]
        System.Threading.Tasks.Task<string> SignInAsync(HelloWcfClient.HelloWcfServiceReference.SignModel model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignServiceChannel : HelloWcfClient.HelloWcfServiceReference.ISignService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignServiceClient : System.ServiceModel.ClientBase<HelloWcfClient.HelloWcfServiceReference.ISignService>, HelloWcfClient.HelloWcfServiceReference.ISignService {
        
        public SignServiceClient() {
        }
        
        public SignServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SignIn(HelloWcfClient.HelloWcfServiceReference.SignModel model) {
            return base.Channel.SignIn(model);
        }
        
        public System.Threading.Tasks.Task<string> SignInAsync(HelloWcfClient.HelloWcfServiceReference.SignModel model) {
            return base.Channel.SignInAsync(model);
        }
    }
}
